In [1]:
import numpy as np
import pandas as pd

/Users/paula/.pyenv/versions/3.8.6/envs/lewagon/lib/python3.8/site-packages/pandas/compat/__init__.py:97: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)

In [7]:
# Load data
street_data = pd.read_csv('data/streets_database.csv', error_bad_lines=False, sep= ';')
street_data

,name,origin,destination,length,oneway,geometry
0,Calle 10,"(-75.5728593, 6.2115169)","(-75.5724985, 6.2113756)",42.867,True,"LINESTRING (-75.5728593 6.2115169, -75.5724984..."
1,Calle 10,"(-75.5705202, 6.2106275)","(-75.570427, 6.2105879)",11.204,True,"LINESTRING (-75.5705202 6.2106275, -75.570427 ..."
2,Carrera 43A,"(-75.5705202, 6.2106275)","(-75.5705604, 6.2105262)",12.109,True,"LINESTRING (-75.5705202 6.2106275, -75.5705604..."
3,Carrera 41,"(-75.5687719, 6.2099661)","(-75.5688022, 6.2098867)",9.443,True,"LINESTRING (-75.5687719 6.2099661, -75.5688021..."
4,Calle 10,"(-75.5687719, 6.2099661)","(-75.568715, 6.2099443)",6.741,True,"LINESTRING (-75.5687719 6.2099661, -75.568715 ..."
...,...,...,...,...,...,...
68744,Medellín - San Jerónimo,"(-75.7086893, 6.3627057)","(-75.7088895, 6.3608552)",207.573,False,"LINESTRING (-75.7086893 6.3627057, -75.7087245..."
68745,68745,"(-75.7086893, 6.3627057)","(-75.708837, 6.3625464)",24.181,False,"LINESTRING (-75.7086893 6.3627057, -75.7087739..."
68746,San Jerónimo-Medellín,"(-75.6909483, 6.338773)","(-75.6898219, 6.33719)",270.387,False,"LINESTRING (-75.6909483 6.338773, -75.6902973 ..."
68747,"['Medellín - San Jerónimo', 'San Jerónimo-Mede...","(-75.6909483, 6.338773)","(-75.7086472, 6.3610709)",3855.673,False,"LINESTRING (-75.6909483 6.338773, -75.6918575 ..."
68748,Medellín - San Jerónimo,"(-75.6909483, 6.338773)","(-75.6957905, 6.3398817)",556.087,False,"LINESTRING (-75.6909483 6.338773, -75.69181519..."